import os
import re
import subprocess

from github import Github
from google import genai
from git import Repo


# ---------------------------
# CONFIG
# ---------------------------

WORKDIR = os.getcwd()
SKILL_DIR = os.path.join(WORKDIR, "skills")

# Must exactly match the issue-form labels in .github/ISSUE_TEMPLATE/*.yml
FIELD_LABELS = ("Plugin", "Skill", "Description")

FIELD_PATTERN = re.compile(
    rf"^#{{1,6}}\s*({'|'.join(FIELD_LABELS)})\s*$",
    re.MULTILINE
)


# ---------------------------
# HELPERS
# ---------------------------

def parse_issue_fields(body: str) -> dict:
    """
    Split a GitHub issue-form body into {label: value} pairs.

    GitHub renders each form field as a markdown heading matching its
    `label` (e.g. "### Skill"), followed by the submitted value. This
    anchors on the known field labels themselves (rather than guessing
    field boundaries from capitalization), so it doesn't break when a
    value is short, is the last field, or happens to contain text that
    looks like a heading.
    """
    matches = list(FIELD_PATTERN.finditer(body))
    fields = {}

    for i, m in enumerate(matches):
        label = m.group(1)
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
        value = body[start:end].strip()
        fields[label] = None if value == "_No response_" else value

    return fields


def load_skill(skill_name: str):
    path = os.path.join(SKILL_DIR, f"{skill_name}.md")
    if not os.path.exists(path):
        return None

    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def run(cmd):
    print(">", " ".join(cmd))
    subprocess.check_call(cmd)


# ---------------------------
# MAIN
# ---------------------------

def main():
    issue_number = int(os.environ["ISSUE_NUMBER"])
    repo_full = os.environ["REPOSITORY"]
    token = os.environ["GITHUB_TOKEN"]

    owner, repo_name = repo_full.split("/")

    # ---------------------------
    # GitHub client
    # ---------------------------
    gh = Github(token)
    repo = gh.get_repo(repo_full)
    issue = repo.get_issue(issue_number)

    body = os.environ["ISSUE_BODY"]

    fields = parse_issue_fields(body)
    plugin = fields.get("Plugin")
    skill = fields.get("Skill")
    description = fields.get("Description")

    # ---------------------------
    # Load skill context
    # ---------------------------
    skill_context = load_skill(skill or "")

    if not skill_context:
        issue.create_comment(f"Skill not found: `{skill}`")
        return

    # ---------------------------
    # Gemini client
    # ---------------------------
    client = genai.Client(
        api_key=os.environ["GEMINI_API_KEY"]
    )

    prompt = """
    You are an expert Java Minecraft plugin developer.

    ## SKILL CONTEXT
    {skill_context}

    ## PROJECT
    Plugin: {plugin}

    ## TASK
    {description}

    ## RULES
    - Return ONLY files in this format:

    <file path="src/.../Example.java">
    public class Example { }
    </file>

    - Follow existing architecture patterns.
    - Do not add explanations. JUST CODE
    """.format(
    skill_context=skill_context,
    plugin=plugin,
    description=description
    )

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    output = response.text

    # ---------------------------
    # Parse files from Gemini output
    # ---------------------------
    files = re.findall(
        r'<file path="(.*?)">(.*?)</file>',
        output,
        re.DOTALL
    )

    if not files:
        issue.create_comment("No files generated by AI.")
        return

    # ---------------------------
    # Create branch
    # ---------------------------
    branch_name = f"ai/issue-{issue_number}"

    repo_git = Repo(WORKDIR)
    repo_git.git.checkout("-b", branch_name)

    # ---------------------------
    # Write files
    # ---------------------------
    for path, content in files:
        full_path = os.path.join(WORKDIR, path)

        os.makedirs(os.path.dirname(full_path), exist_ok=True)

        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content.strip())

        print(f"Written: {path}")

    # ---------------------------
    # Commit changes
    # ---------------------------
    repo_git.git.add(all=True)
    repo_git.index.commit(f"AI: Implement {skill} for issue #{issue_number}")

    repo_git.git.push("--set-upstream", "origin", branch_name)

    # ---------------------------
    # Create PR
    # ---------------------------
    pr = repo.create_pull(
        title=f"[AI] {skill} - Issue #{issue_number}",
        body=f"""
AI-generated implementation.

Plugin: {plugin}
Skill: {skill}

Closes #{issue_number}
""",
        head=branch_name,
        base="main"
    )

    # ---------------------------
    # Comment back on issue
    # ---------------------------
    issue.create_comment(
        f"""AI Implementation Complete!

- Branch: `{branch_name}`
- PR: {pr.html_url}
"""
    )

    print("DONE")


if __name__ == "__main__":
    main()